### ISSUE TITLE
How to get results as an array

### ISSUE THREAD

**Issue by Chillifish** [ActiveCampaign/postmark-php#105]
This is down to my lack of knowledge rather than anything else, but I'm really struggling to get results in a useable format. Following the docs here: https://github.com/ActiveCampaign/postmark-php/wiki/Getting-Started#about-responses-from-api-calls

I want an array of results, however, all I can get is a DynamicResponseModel Object. I can't get the results out as the CaseInsensitveArray with the results is private. I can't find a getter function. I must be missing something obvious, please help!

Trying to get an array of clicks just provides the below

`Postmark\Models\DynamicResponseModel Object
(
    [_container:Postmark\Models\CaseInsensitiveArray:private] => Array
        (
            [totalcount] => 3260
            [clicks] => Array
                (
                    [0] => Array
`
I just can't seem to get the clicks array. If I use `$results['clicks']` as suggested in the docs, I just get another object:

`Array
(
    [0] => Postmark\Models\DynamicResponseModel Object
        (
            [_container:Postmark\Models\CaseInsensitiveArray:private] => Array
                (`

**Comment by ewood-ac** [comment]
Hopefully you have solved this already. This issues forum is for reporting bugs. This does not appear to be a bug.
When using the  $results['clicks'] you are likely getting a list of Objects back because there are 3260 clicks. In php you will often see something like $results['clicks'][0] to get the first of those items. Otherwise you could do a var_dump to see what the object contains. Hope this helps.
