### ISSUE TITLE
 "Trying to access array offset"

### ISSUE THREAD

**Issue by MatthewArnott** [ActiveCampaign/postmark-php#79]
Hi, I have been trying to send an email out on Kartra using Postmark Servers but I keep getting this error, the email send to another list with around 2k people but this one is failing to send. The email is going to around 12k people. I am presented with the following message:

"Unfortunately, the sendout has failed to go through and your gateway returned the following error message: "Postmark general exception: Trying to access array offset on value of type null in /var/www/kartra/1614264772/libraries_not_ci/vendor/wildbit/postmark-php/src/Postmark/PostmarkClientBase.php at line 168".
 
IMPORTANT: This is NOT a Kartra-generated error. Therefore, we recommend you to contact your gateway's support team to find out what this error means, and how to solve it."

Any ideas what the cause of this might be?

Cheers
Matt

**Comment by rianvdm** [comment]
Hey Matt, could you reach out to support@postmarkapp.com and we'll look into this? Thanks!

**Comment by vladsandu** [comment]
@MatthewArnott thanks for bringing up this issue! This exception has been generated in the error handling logic used when sending requests to our API. Based on the [code path](https://github.com/wildbit/postmark-php/blob/136e3d0884411ca23d0bac02470cfa1d14be676c/src/Postmark/PostmarkClientBase.php#L168) in the error message, some requests you have been making failed, *I'm guessing* with a _422 Unprocessable Entity_ or another non-standard response code. 

A more descriptive and useful error message should have been returned instead of that generic exception. I believe this may have been caused by some [backwards incompatible changes](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access) present in more recent versions of PHP (7.4+) that our error handling code may not fully support yet. We will look into fixing these error messages in a future release.

**Comment by ewood-ac** [comment]
Closed due to age. If this persists - please let us know.

**Comment by flangfeldt** [comment]
This is still a problem. The code assumes that the $body is a valid array with an 'ErrorCode' key. Apparently this is not always the case. 

On line 181 of PostmarkClientBase.php we see `$ex->setPostmarkApiErrorCode($body['ErrorCode']);`.
There should be a check on `$body['ErrorCode']`, something like `$body['ErrorCode'] ?? ''` where the empty string could be a default message.
